ArabicTextAnalyzer/Controllers/TrainController.cs
using ArabicTextAnalyzer.Business.Provider;
using ArabicTextAnalyzer.Domain;
using ArabicTextAnalyzer.Domain.Models;
using ArabicTextAnalyzer.Models.Repository;
using ArabicTextAnalyzer.Models;
using ArabicTextAnalyzer.ViewModels;
using Dapper;
using Newtonsoft.Json;
using OADRJNLPCommon.Business;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using OADRJNLPCommon.Models;
using System.Threading.Tasks;
using ArabicTextAnalyzer.Contracts;
using ArabicTextAnalyzer.BO;
using System.Net.Mail;
using Newtonsoft.Json.Linq;
using System.Globalization;
using System.Web.SessionState;
using ArabicTextAnalyzer.Content.Resources;
using MimeKit;
using System.Text.RegularExpressions;
using Microsoft.AspNet.Identity.Owin;
using static ArabicTextAnalyzer.BO.Arabizer;
// using ScrapyWeb.Business;

namespace ArabicTextAnalyzer.Controllers
{
    [Authorize]
    // [AuthenticateFilter]
    [SessionState(SessionStateBehavior.ReadOnly)]
    public class TrainController : BaseController
    {
        // global lock to queur concurrent access
        private static Object thisLock = new Object();

        // authentication in constructor
        IAuthenticate _IAuthenticate;
        IRegisterApp _IRegister;
        public TrainController()
        {
            _IAuthenticate = new AuthenticateConcrete();
            _IRegister = new RegisterAppConcrete();
        }

        // data access mode (ef-sql, dapper-sql, xml)
        // AccessMode _accessMode = AccessMode.dappersql;

        // GET: Train
        [Authorize]
        public ActionResult Index()
        {
            //
            var userId = User.Identity.GetUserId();

            // token management
            ManageToken(userId);

            //
            string errMessage = string.Empty;
            List<RegisterApp> _registerApp = _IRegister.ListofApps(userId).ToList();
            ViewBag.registerApp = _registerApp;

            // send size of corpus & co-data
            @ViewBag.CorpusSize = new TextFrequency().GetCorpusNumberOfLine();
            @ViewBag.CorpusWordCount = new TextFrequency().GetCorpusWordCount();
            @ViewBag.BidictSize = new TextFrequency().GetBidictNumberOfLine();
            var arabiziEntriesCount = loaddeserializeM_ARABIZIENTRY_DAPPERSQL().Count;
            @ViewBag.ArabiziEntriesCount = arabiziEntriesCount;
            @ViewBag.RatioLatinWordsOnEntries = loaddeserializeM_ARABICDARIJAENTRY_LATINWORD_DAPPERSQL().Where(m => String.IsNullOrWhiteSpace(m.Translation) == true).ToList().Count / (double)arabiziEntriesCount;

            @ViewBag.EntitiesCount = new TextFrequency().GetEntitiesCount();

            // deserialize/send twingly accounts
            @ViewBag.TwinglyAccounts = loaddeserializeM_TWINGLYACCOUNT_DAPPERSQL();

            // themes : deserialize/send list of themes, plus send active theme, plus send list of tags/keywords
            var userXtrctThemes = new Arabizer().loaddeserializeM_XTRCTTHEME_DAPPERSQL(userId);
            List<M_XTRCTTHEME_KEYWORD> xtrctThemesKeywords = new Arabizer().loaddeserializeM_XTRCTTHEME_KEYWORD_Active_DAPPERSQL(userId);
            var userActiveXtrctTheme = userXtrctThemes.Find(m => m.CurrentActive == "active");
            @ViewBag.UserXtrctThemes = userXtrctThemes;
            @ViewBag.XtrctThemesPlain = userXtrctThemes.Select(m => new SelectListItem { Text = m.ThemeName.Trim(), Selected = m.ThemeName.Trim() == userActiveXtrctTheme.ThemeName.Trim() ? true : false });
            @ViewBag.UserActiveXtrctTheme = userActiveXtrctTheme;
            @ViewBag.ActiveXtrctThemeNegTags = xtrctThemesKeywords.Where(m => m.Keyword_Type == "NEGATIVE" || m.Keyword_Type == "OPPOSE" || m.Keyword_Type == "EXPLETIVE" || m.Keyword_Type == "SENSITIVE").ToList();
            @ViewBag.ActiveXtrctThemePosTags = xtrctThemesKeywords.Where(m => m.Keyword_Type == "POSITIVE" || m.Keyword_Type == "SUPPORT").ToList();
            @ViewBag.ActiveXtrctThemeOtherTags = xtrctThemesKeywords.Where(m => m.Keyword_Type != "POSITIVE" && m.Keyword_Type != "SUPPORT" && m.Keyword_Type != "NEGATIVE" && m.Keyword_Type != "OPPOSE" && m.Keyword_Type != "EXPLETIVE" && m.Keyword_Type != "SENSITIVE").ToList();

            // Fetch the data for fbPages for all themes for that user
            var fbFluencerAsTheme = new Arabizer().loadDeserializeT_FB_INFLUENCERs_DAPPERSQL(userId);
            ViewBag.AllInfluenceVert = fbFluencerAsTheme;

            // communication
            @ViewBag.showAlertWarning = TempData["showAlertWarning"] != null ? TempData["showAlertWarning"] : false;
            @ViewBag.showAlertSuccess = TempData["showAlertSuccess"] != null ? TempData["showAlertSuccess"] : false;
            @ViewBag.msgAlert = TempData["msgAlert"] != null ? TempData["msgAlert"] : String.Empty;
            TempData.Remove("showAlertWarning");
            TempData.Remove("showAlertSuccess");
            TempData.Remove("msgAlert");

            // working data entries count
            List<LM_CountPerThemePerUser> entriesCountsperThemePerUser = new Arabizer().loaddeserializeM_ARABICDARIJAENTRY_CountPerThemePerUser_DAPPERSQL(userId);
            @ViewBag.EntriesCountsperThemePerUser = entriesCountsperThemePerUser;

            // fb pages comments count
            List<LM_CountPerInfluencer> commentsCountsPerInfluencer = new Arabizer().loaddeserializeT_FB_Comments_CountPerInfluencer_DAPPERSQL(userId);
            @ViewBag.CommentsCountsPerInfluencer = commentsCountsPerInfluencer;

            // fb pages posts count
            List<LM_CountPerInfluencer> postsCountsPerInfluencer = new Arabizer().loaddeserializeT_FB_Posts_CountPerInfluencer_DAPPERSQL(userId);
            @ViewBag.PostsCountsPerInfluencer = postsCountsPerInfluencer;

            // scocial searc posys count & comment count
            @ViewBag.PostsCounts = new Arabizer().loaddeserializeT_FB_Posts_Count_DAPPERSQL();
            @ViewBag.CommentsCounts = new Arabizer().loaddeserializeT_FB_Comments_Count_DAPPERSQL();

            //
            @ViewBag.NersWithCounts = new Arabizer().loaddeserializeM_XTRCTTHEME_KEYWORD_StatAllNersCounts_DAPPERSQL();

            // DBG
            ViewBag.UserName = User.Identity.GetUserName();

            //
            return View();
        }

        [Authorize]
        public ActionResult IndexTranslateArabizi()
        {
            //
            var userId = User.Identity.GetUserId();

            // themes : deserialize/send list of themes, plus send active theme, plus send list of tags/keywords
            var userXtrctThemes = new Arabizer().loaddeserializeM_XTRCTTHEME_DAPPERSQL(userId);
            List<M_XTRCTTHEME_KEYWORD> xtrctThemesKeywords = new Arabizer().loaddeserializeM_XTRCTTHEME_KEYWORD_Active_DAPPERSQL(userId);
            var userActiveXtrctTheme = userXtrctThemes.Find(m => m.CurrentActive == "active");
            @ViewBag.UserXtrctThemes = userXtrctThemes;
            @ViewBag.XtrctThemesPlain = userXtrctThemes.Select(m => new SelectListItem { Text = m.ThemeName.Trim(), Selected = m.ThemeName.Trim() == userActiveXtrctTheme.ThemeName.Trim() ? true : false });
            @ViewBag.UserActiveXtrctTheme = userActiveXtrctTheme;
            @ViewBag.ActiveXtrctThemeNegTags = xtrctThemesKeywords.Where(m => m.Keyword_Type == "NEGATIVE" || m.Keyword_Type == "OPPOSE" || m.Keyword_Type == "EXPLETIVE" || m.Keyword_Type == "SENSITIVE").ToList();
            @ViewBag.ActiveXtrctThemePosTags = xtrctThemesKeywords.Where(m => m.Keyword_Type == "POSITIVE" || m.Keyword_Type == "SUPPORT").ToList();
            @ViewBag.ActiveXtrctThemeOtherTags = xtrctThemesKeywords.Where(m => m.Keyword_Type != "POSITIVE" && m.Keyword_Type != "SUPPORT" && m.Keyword_Type != "NEGATIVE" && m.Keyword_Type != "OPPOSE" && m.Keyword_Type != "EXPLETIVE" && m.Keyword_Type != "SENSITIVE").ToList();

            // Fetch the data for fbPages for all themes for that user
            var fbFluencerAsTheme = new Arabizer().loadDeserializeT_FB_INFLUENCERs_DAPPERSQL(userId);
            ViewBag.AllInfluenceVert = fbFluencerAsTheme;

            // working data entries count
            List<LM_CountPerThemePerUser> entriesCountsperThemePerUser = new Arabizer().loaddeserializeM_ARABICDARIJAENTRY_CountPerThemePerUser_DAPPERSQL(userId);
            @ViewBag.EntriesCountsperThemePerUser = entriesCountsperThemePerUser;

            // fb pages comments count
            List<LM_CountPerInfluencer> commentsCountsPerInfluencer = new Arabizer().loaddeserializeT_FB_Comments_CountPerInfluencer_DAPPERSQL(userId);
            @ViewBag.CommentsCountsPerInfluencer = commentsCountsPerInfluencer;

            // fb pages posts count
            List<LM_CountPerInfluencer> postsCountsPerInfluencer = new Arabizer().loaddeserializeT_FB_Posts_CountPerInfluencer_DAPPERSQL(userId);
            @ViewBag.PostsCountsPerInfluencer = postsCountsPerInfluencer;

            // scocial searc posys count & comment count
            @ViewBag.PostsCounts = new Arabizer().loaddeserializeT_FB_Posts_Count_DAPPERSQL();
            @ViewBag.CommentsCounts = new Arabizer().loaddeserializeT_FB_Comments_Count_DAPPERSQL();

            // DBG
            ViewBag.UserName = User.Identity.GetUserName();

            return View();
        }

        [AllowAnonymous]
        public ActionResult IndexTranslateArabiziFree()
        {
            return View();
        }

        [Authorize]
        // [NonAction] // tmp
        public ActionResult IndexStats()
        {
            //
            var userId = User.Identity.GetUserId();


ArabicTextAnalyzer/Views/Train/IndexFBs.cshtml
@using ArabicTextAnalyzer.Content.Resources
@{
    ViewBag.Title = R.FacebookPages;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles {

    @* mandatory : vertical menus, ... *@
    @Styles.Render("~/Content/css_train")

    @* datatables.net dependencies *@
    <link href="https://cdn.datatables.net/select/1.2.3/css/select.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.4.2/css/buttons.dataTables.min.css" />
}

@section scripts {
    
    @*  datatables.net dependencies *@
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/mark.js/8.6.0/jquery.mark.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/datatables.mark.js/2.0.0/datatables.mark.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/select/1.2.3/js/dataTables.select.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.flash.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>

    @* the scripts that load data into the partial view (using datatables.net) and allow displaying/selecting/filtering *@
    @Scripts.Render("~/bundles/js_train")
    <script type="text/javascript" src="~/Scripts/mysite_train_keywordfiltering.js"></script>
    @Scripts.Render("~/bundles/js_train_fbs")
}

<h2>@ViewBag.Title.</h2>
<h4>@R.UseFacebookPagesEtc</h4>
<hr />

<!-- Place where you will insert your partial -->
<div id="partialPlaceHolder" style="display:inline;"> </div>

ArabicTextAnalyzer/Views/Train/IndexSplash.cshtml

@{
    ViewBag.Title = "";
}


@section styles {

    @* mandatory : vertical menus, ... *@
    @Styles.Render("~/Content/css_train")
}

ArabicTextAnalyzer/Views/Train/IndexTranslateArabizi.cshtml
@using ArabicTextAnalyzer.Domain.Models
@using ArabicTextAnalyzer.Content.Resources
@model M_ARABIZIENTRY
@{
    ViewBag.Title = R.TranslateArabizi;
    Layout = "~/Views/Shared/_Layout.cshtml";

    @* switch to FR so date can match the globalization set in web.config, otherwise arabizi date is ko *@
    //Culture = UICulture = "fr-FR";
}

@section styles {

    @* mandatory : vertical menus, ... *@
    @Styles.Render("~/Content/css_train")

    @Styles.Render("~/Content/css_train_tagsinput")

    <link href="https://cdn.datatables.net/select/1.2.3/css/select.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.4.2/css/buttons.dataTables.min.css" />
}

@section scripts {

    <script type="text/javascript" src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/mark.js/8.6.0/jquery.mark.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/datatables.mark.js/2.0.0/datatables.mark.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/select/1.2.3/js/dataTables.select.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.html5.min.js"></script>

    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.flash.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>

    @Scripts.Render("~/bundles/js_train_translate_single")
    @Scripts.Render("~/bundles/js_train_tagsinput");
}

<h2>@ViewBag.Title.</h2>
<h4>@R.TranslateArabiziToArabicEtc</h4>
<hr />

<!-- aribizi translate single -->
@using (Html.BeginForm("TrainStepOneAjax", "Train", new { mainEntity = @ViewBag.UserActiveXtrctTheme.ThemeName.Trim() }, FormMethod.Post, new { id = "trainform" }))
{
    <!-- textarea input text & button go -->
    <div class="panel panel-default active">
        <div class="panel-heading">@R.Arabizi</div>
        <div class="panel-body" style="padding: 0;">
            <div class="input-group">
                @Html.TextAreaFor(m => m.ArabiziText, new { id = "SentenceIn", style = "resize:none", rows = 2, @class = "form-control custom-control", @required = "required", @placeholder = R.TypeArabiziTextAndClickGo })
                @Html.HiddenFor(m => m.ArabiziEntryDate, new { @Value = System.DateTime.Now.ToString("yyyy-MM-dd HH:MM:ss") })
                @Html.HiddenFor(m => m.ID_XTRCTTHEME, new { @Value = ViewBag.UserActiveXtrctTheme.ID_XTRCTTHEME })
                <span class="input-group-addon btn btn-primary" onclick="document.forms['trainform'].dispatchEvent(new Event('submit'));">Go</span>
            </div>
        </div>
    </div>
}

<!-- translated text area with option to edit -->
<table class="posts table table-striped table-hover table-bordered " role="grid" style="margin-left: auto; margin-right: auto; display: none;">
    <thead>
        <tr class="header" role="row"><th class="center top col50prc arabic-text sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Arabic: activate to sort column ascending" style="width: 248px;">Arabic</th><th class="center top col100px arabic-text entitiestype sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="NER Types: activate to sort column ascending" style="width: 94px;">NER Types</th><th class="center top col130px arabic-text entities sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Entities: activate to sort column ascending" style="width: 124px;">Entities</th></tr>
    </thead>
    <tbody>
        <tr role="row">
            <td class="top arabicdarija">
                <div class="input-group">
                    <span class="input-group-addon btn btn-primary visibilityhidden" title="Contribute your own improvement of this translation" data-target="#modalConfirmContrib" data-toggle="modal"><i class="fa fa-edit"></i></span>
                    <textarea id="improvetranslation" style="resize:none; direction:rtl;" class="form-control" title="Edit this area to improve the translation"></textarea>
                </div>
            </td>
            <td class="arabic-text top entitiestype"><span class="label label-info"></span></td>
            <td class="arabic-text top entities"><span class="label label-info"></span></td>
        </tr>
    </tbody>
</table>
@* <input id="allners" type="text" data-role="tagsinput" style="min-height: 100px;" /> *@

<!-- modal confirmation save translation contrib -->
<div id="modalConfirmContrib" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" style="color:darkblue;">Save Translation Contribution</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="contrib">Are you sure you want to save your own translation</label>
                    <input class="form-control" id="contrib" name="contrib" readonly="readonly" required="required" type="text" value="Default" style="direction:rtl;">
                </div>
                <button type="button" class="btn btn-default btn-success" onclick="saveTranslationContribution();">Save</button>
            </div>
        </div>
    </div>
</div>

<!-- misc area to say success -->
<div id="miscareasuccess" class="alert alert-success alert-dismissable" style="display: none;">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>@R.Success!</strong> <p style="display: inline;"></p>
</div>

<!-- misc areas to report warnings/errors -->
<div id="miscareaerror" class="alert alert-warning alert-dismissable margin-bottom-0" style="display: none;">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>@R.Warning!</strong> <p style="display: inline;"></p>
</div>

ArabicTextAnalyzer/Views/Train/IndexTranslateArabiziFree.cshtml

@using ArabicTextAnalyzer.Domain.Models
@using ArabicTextAnalyzer.Content.Resources
@model M_ARABIZIENTRY
@{
    ViewBag.Title = R.TranslateArabizi;
    Layout = "~/Views/Shared/_LayoutFree.cshtml";
}

@section styles {

    @* mandatory : vertical menus, ... *@
    @Styles.Render("~/Content/css_train")

    @Styles.Render("~/Content/css_train_tagsinput")

    <link href="https://cdn.datatables.net/select/1.2.3/css/select.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.4.2/css/buttons.dataTables.min.css" />
}

@section scripts {

    <script type="text/javascript" src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/mark.js/8.6.0/jquery.mark.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/datatables.mark.js/2.0.0/datatables.mark.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/select/1.2.3/js/dataTables.select.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.html5.min.js"></script>

    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.flash.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>

    @Scripts.Render("~/bundles/js_train_translate_single")
    @Scripts.Render("~/bundles/js_train_tagsinput");
}

<h2>@ViewBag.Title.</h2>
<h4>@R.TranslateArabiziToArabicEtc</h4>
<hr />

<!-- aribizi translate single -->
@using (Html.BeginForm("TrainStepOneAjaxFree", "Train", null, FormMethod.Post, new { id = "trainform" }))
{
    <!-- textarea input text & button go -->
    <div class="panel panel-default active">
        <div class="panel-heading">@R.Arabizi</div>
        <div class="panel-body" style="padding: 0;">
            <div class="input-group">
                @Html.TextAreaFor(m => m.ArabiziText, new { id = "SentenceIn", style = "resize:none", rows = 2, @class = "form-control custom-control", @required = "required", @placeholder = R.TypeArabiziTextAndClickGo })
                @Html.HiddenFor(m => m.ArabiziEntryDate, new { @Value = System.DateTime.Now.ToString("yyyy-MM-dd HH:MM:ss") })
                <span class="input-group-addon btn btn-primary" onclick="document.forms['trainform'].dispatchEvent(new Event('submit'));">Go</span>
            </div>
        </div>
    </div>
}

<!-- translated text area with option to edit -->
<table class="posts table table-striped table-hover table-bordered " role="grid" style="margin-left: auto; margin-right: auto; display: none;">
    <thead>
        <tr class="header" role="row"><th class="center top col50prc arabic-text sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Arabic: activate to sort column ascending" style="width: 248px;">Arabic</th><th class="center top col100px arabic-text entitiestype sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="NER Types: activate to sort column ascending" style="width: 94px;">NER Types</th><th class="center top col130px arabic-text entities sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Entities: activate to sort column ascending" style="width: 124px;">Entities</th></tr>
    </thead>
    <tbody>
        <tr role="row">
            <td class="top arabicdarija">
                <div class="input-group">
                    <span class="input-group-addon btn btn-primary visibilityhidden" title="Contribute your own improvement of this translation" data-target="#modalConfirmContrib" data-toggle="modal"><i class="fa fa-edit"></i></span>
                    <textarea id="improvetranslation" style="resize:none; direction:rtl;" class="form-control" title="Edit this area to improve the translation"></textarea>
                </div>
            </td>
            <td class="arabic-text top entitiestype"><span class="label label-info"></span></td>
            <td class="arabic-text top entities"><span class="label label-info"></span></td>
        </tr>
    </tbody>
</table>

<!-- modal confirmation save translation contrib -->
<div id="modalConfirmContrib" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" style="color:darkblue;">Save Translation Contribution</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="contrib">Are you sure you want to save your own translation</label>
                    <input class="form-control" id="contrib" name="contrib" readonly="readonly" required="required" type="text" value="Default" style="direction:rtl;">
                </div>
                <button type="button" class="btn btn-default btn-success" onclick="saveTranslationContribution();">Save</button>
            </div>
        </div>
    </div>
</div>

<!-- misc area to say success -->
<div id="miscareasuccess" class="alert alert-success alert-dismissable" style="display: none;">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>@R.Success!</strong> <p style="display: inline;"></p>
</div>

<!-- misc areas to report warnings/errors -->
<div id="miscareaerror" class="alert alert-warning alert-dismissable margin-bottom-0" style="display: none;">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>@R.Warning!</strong> <p style="display: inline;"></p>
</div>
